# Generated by Django 5.2 on 2025-04-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('quizzes', '0003_remove_quiz_classroom'),
        ('users', '0002_remove_userprofile_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
