# Generated by Django 5.2 on 2025-04-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_classroom_quiz_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='classroom',
        ),
    ]
